name: Push Docker image to Docker Hub
on:
  push:
    branches:
      - master

jobs:
  push:
    env:
      DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
      DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Login to Docker Hub
        uses: docker/login-action@v1
        with:
          username: theola4
          password: dckr_pat_PkMaVCCzXSvIFSUsSqrwuTGf4zs
      - name: Build and push Docker image
        uses: docker/build-push-action@v2
        with:
          context: .
          push: true
          tags: username/repository:latest
